name: flutter_account_book_app
description: Flutter 製の個人用家計簿アプリ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_mobile_ads: ^0.12.1
  # sqfentity の自動生成コードの url が String 型のため
  # 0.13 系にはバージョンを上げられない
  # 参考：https://pub.dev/packages/http/changelog
  http: ^0.12.2
  provider: ^5.0.0
  sqfentity: ^1.4.0+3
  sqfentity_gen: ^1.4.0+2

dev_dependencies:
  build_runner: ^1.6.5
  build_verify: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
